### ISSUE TITLE
Doesn't work in Google Chrome => use strict mode

### ISSUE THREAD

**Issue by blackgwe** [vegarringdal/aurelia-fusebox-test#3]
Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

Version 48.0.2547.0 dev (64-bit)
Linux (Debian)

**Comment by vegarringdal** [comment]
@blackgwe 
Thx for the heads up, there will be an official skeleton navigation with use of fuse box soon, without my grid in it, made this while doing a lot of testing to get it to load :-)

**Comment by vegarringdal** [comment]
@blackgwe 
Any reason why you are running a old version of chrome ?

**Comment by blackgwe** [comment]
@vegarringdal No problem - Thank you! It was my computer@work / stable Ubuntu Linux.

btw works properly on Arch Linux [Version 54.0.2840.71 (64-bit)] on my computer@home.

**Comment by vegarringdal** [comment]
Fixed this to work, now it even works in IE11

**Comment by vegarringdal** [comment]
@blackgwe Please give it a test, 1 issue was the loader, 2 was fusebox dev server

**Comment by blackgwe** [comment]
@vegarringdal Everything works properly - THANK YOU VERY MUCH!
