### ISSUE TITLE
silly question: adding plugins

### ISSUE THREAD

**Issue by AngelMunoz** [vegarringdal/aurelia-fusebox-test#4]
Hello, amazing work!
silly question, for each plugin you add should you use a different bundle? or could they come in the same bundle?

**Comment by vegarringdal** [comment]
Hi
It really depends on the plugin I guess, in my plugin ```aurelia-v-grid``` I have custom-elements, custom-attributes and css that I need to have added to bundle.

Kinda hoping this will make it a lot easier:
https://github.com/fuse-box/fuse-box/issues/170

Only been trying out fusebox this week, so there is a lot I dont know yet :-)

**Comment by AngelMunoz** [comment]
great discussion there I hope this comes soon 😸 I'd like to test a similar setup but inside electron given the fact that the Aurelia-cli require's conflicts with electron require's.
thanks !
